version: '3.3'
services:
  zookeeper:
    image: zookeeper:3.5

  kafka:
    image: bitnami/kafka:2
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_BROKER_ID: '1001'
      KAFKA_CFG_RESERVED_BROKER_MAX_ID: '1002'
      KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE: 'true'
      KAFKA_CFG_LOG_CLEANER_ENABLE: 'true'
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: '30000'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://0.0.0.0:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
    links:
      - zookeeper
    ports:
      - 9092:9092

  kafka-manager:
    image: solsson/kafka-manager:latest
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - 9000:9000
    links:
      - zookeeper
      - kafka

  elastic:
    image: elastic/elasticsearch:7.10.1
    ports:
      - 9200:9200

  catalog:
    build:
      context: catalog
    links:
      - elastic
    volumes:
      - ./catalog:/app

  catalog-integration:
    build:
      context: catalog-integration
    links:
      - catalog
      - kafka
    volumes:
      - ./catalog-integration:/app

  compras:
    build:
      context: compras
    links:
      - kafka
    volumes:
      - ./compras:/app

  items:
    build:
      context: items
    links:
      - kafka
    volumes:
      - ./items:/app

  pagamentos:
    build:
      context: pagamentos
    links:
      - kafka
    volumes:
      - ./pagamentos:/app

  relatorio-integration:
    build:
      context: relatorio-integration
    links:
      - kafka
      - relatorios
      - usuarios
      - compras
      - pagamentos
    volumes:
      - ./relatorio-integration:/app

  relatorios:
    build:
      context: relatorios
    volumes:
      - ./relatorios:/app

  usuarios:
    build:
      context: usuarios
    volumes:
      - ./usuarios:/app

